name: tester_laravel
services:
  db:
    image: mysql:8.0
    container_name: DbMysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_test
      MYSQL_USER: usersql
      MYSQL_PASSWORD: 123qwe!@
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app_tester
    container_name: Application
    working_dir: /var/www/html
    restart: on-failure
    volumes:
      - ./vendor:/var/www/html/vendor
    ports:
      - "8000:80"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=asugamele_laravel
      - DB_USERNAME=asugamele
      - DB_PASSWORD=123qwe!@
    depends_on:
      - db
volumes:
  db_data:
